[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 12
        path = 'page'
    [en.taxonomies]
        author = 'author'
        category = 'categories'
        series = 'series'
        tag = 'tags'

[cn]
    contentDir = 'content/cn'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '中文'
    [id.pagination]
        disableAliases = false
        pagerSize = 12
        path = 'laman'
    [id.params.feed]
        flowlines = false

[fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Francais'
